### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Robo-Ryan** [jmalon10/Discover-fy#35]

**Comment by Robo-Ryan** [comment]
![Image](https://github.com/user-attachments/assets/ed9f9405-20d4-4867-8e77-baa3dbe4b933)

- [ ] title: Welcome to discover-fy
- [ ] paragraph text: welcome message
- [ ] images of aritsts
- [ ] button for beginning "Discover flow"
- [ ] Nav can also be clicked to discover your next playlist

**Comment by lekshmisree89** [comment]
done
