### ISSUE TITLE
Add Tailwind properties to our components

### ISSUE THREAD

**Issue by Robo-Ryan** [jmalon10/Discover-fy#57]

**Comment by Diivvuu** [comment]
Hey  @Robo-Ryan  could you please **explain** a little brief and assign this one to me? Looking forward to contributing to it

**Comment by Robo-Ryan** [comment]
- [ ] add properties to top tracks card component 
- [ ] add properties to search component

**Comment by Robo-Ryan** [comment]
Hey Divyanshu,

I think you may be looking at the wrong account or project. We are building
an app for a bootcamp project. Is that the project you're referring to?

Best,
Ryan

**Comment by Diivvuu** [comment]
Thanks for getting back to me! I'm actually looking to contribute to open-source projects and thought this might be a good fit. If this is part of an open-source initiative, I'd love to help out.
